Use try/except instead of 'if' to check var existence
Before, I had `if climo_ptiles` to see if that variable was defined, but
I was getting this error:

    ValueError: The truth value of an array with more than one element is
    ambiguous. Use a.any() or a.all()

I've switched to just using a try/except to try using the `climo_ptiles`
variable.